import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("tour/", "routes/tourdetails.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("bookings", "routes/booking.tsx"),
  route("booking", "routes/bookings.tsx"),
  route("unauthorized", "routes/unauthorized.tsx"),
  route("destinations","routes/destinations.tsx"),
  route("destinations/:slug", "routes/destinations/[slug].tsx"),
  route("our-blogs", "routes/blogs.tsx"),
  route("blogs/:slug", "routes/blogs/[slug].tsx"),
  route("privacy-policy", "routes/privacypolicy.tsx"),
  route("contact", "routes/contact.tsx"),
  route("about-us", "routes/about.tsx"),
  route("terms-&-conditions", "routes/terms.tsx"),
  route("cancellation-policy", "routes/cancellation.tsx"),
  route("disclaimer", "routes/disclaimer.tsx"),
  route("payments", "routes/payments.tsx"),
  route(":type", "routes/[type].tsx"),
  route("admin", "routes/admin/_layout.tsx", [
    index("routes/admin/dashboard.tsx"),
    route("itineraries", "routes/admin/itineraries.tsx"),
    route("itineraries/new", "routes/admin/itineraries/new.tsx"),
    route("itineraries/update/:id", "routes/admin/itineraries/update/[id].tsx"),
    route("destinations", "routes/admin/destinations.tsx"),
    route("destinations/new", "routes/admin/destinations/new.tsx"),
    route("destinations/:id", "routes/admin/destinations/[id].tsx"),
    route("users", "routes/admin/users.tsx"),
    route("users/:id", "routes/admin/users/[id].tsx"),
    route("bookings", "routes/admin/bookings.tsx"),
    route("bookings/:id", "routes/admin/bookings/[id].tsx"),
    route("cms", "routes/admin/cms.tsx"),
    route("blog", "routes/admin/blog.tsx"),
    route("blog/new", "routes/admin/blog/new.tsx"),
    route("blog/edit/:id", "routes/admin/blog/edit/[id].tsx"),
    route("blog/:id", "routes/admin/blog/[id].tsx"),
    route("marketing", "routes/admin/marketing.tsx"),
    route("reviews", "routes/admin/reviews.tsx"),
    route("enquiries", "routes/admin/enquiries.tsx"),
    route("guides", "routes/admin/guides.tsx"),
    route("analytics", "routes/admin/analytics.tsx"),
    route("settings", "routes/admin/settings.tsx"),
  ]),
] satisfies RouteConfig;
