import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("destination/:slug", "routes/destination.tsx"),
  route("tour/", "routes/tourdetails.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("unauthorized", "routes/unauthorized.tsx"),
  route("admin", "routes/admin/_layout.tsx", [
    route("dashboard", "routes/admin/dashboard.tsx"),
    route("itineraries", "routes/admin/itineraries.tsx"),
    route("itineraries/new", "routes/admin/itineraries/new.tsx"),
    route("itineraries/:id", "routes/admin/itineraries/[id].tsx"),
    route("destinations", "routes/admin/destinations.tsx"),
    route("destinations/new", "routes/admin/destinations/new.tsx"),
    route("destinations/:id", "routes/admin/destinations/[id].tsx"),
    route("users", "routes/admin/users.tsx"),
    route("users/:id", "routes/admin/users/[id].tsx"),
    route("bookings", "routes/admin/bookings.tsx"),
    route("bookings/:id", "routes/admin/bookings/[id].tsx"),
    route("payments", "routes/admin/payments.tsx"),
    route("cms", "routes/admin/cms.tsx"),
    route("blog", "routes/admin/blog.tsx"),
    route("blog/new", "routes/admin/blog/new.tsx"),
    route("blog/:id", "routes/admin/blog/[id].tsx"),
    route("marketing", "routes/admin/marketing.tsx"),
    route("reviews", "routes/admin/reviews.tsx"),
    route("guides", "routes/admin/guides.tsx"),
    route("analytics", "routes/admin/analytics.tsx"),
    route("settings", "routes/admin/settings.tsx"),
  ]),
] satisfies RouteConfig;
